package hmongo

import "go.mongodb.org/mongo-driver/mongo"

type M map[string]interface{}

type HCursor struct {
	Cursor *mongo.Cursor
}

type Index struct {
	DB         string
	Collection string
	Keys       []string
	Unique     bool
}

type Config struct {
	Url         string `json:"url"`
	DBName      string `json:"db_name"`
	User        string `json:"user"`
	Password    string `json:"password"`
	MaxPoolSize int    `json:"max_pool_size"`
}

// InsertOneResult is the result type returned by an InsertOne operation.
type InsertOneResult struct {
	// The _id of the inserted document. A value generated by the driver will be of type primitive.ObjectID.
	InsertedID interface{}
}

// InsertManyResult is a result type returned by an InsertMany operation.
type InsertManyResult struct {
	// The _id values of the inserted documents. Values generated by the driver will be of type primitive.ObjectID.
	InsertedIDs []interface{}
}

// UpdateResult is the result type returned from UpdateOne, UpdateMany, and ReplaceOne operations.
type UpdateResult struct {
	MatchedCount  int64       // The number of documents matched by the filter.
	ModifiedCount int64       // The number of documents modified by the operation.
	UpsertedCount int64       // The number of documents upserted by the operation.
	UpsertedID    interface{} // The _id field of the upserted document, or nil if no upsert was done.
}

// DeleteResult is the result type returned by DeleteOne and DeleteMany operations.
type DeleteResult struct {
	DeletedCount int64 `bson:"n"` // The number of documents deleted.
}
